# my window manager config ;)
set -sg escape-time 0

unbind C-b
unbind C-a
set -g prefix C-a

# form vim/tmux d/y buffer sync
set -g focus-events

bind-key C-a last-window

unbind |
bind | split-window -h
unbind -
bind - split-window -v

# vi for copy mode
setw -g mode-keys vi

# vi for command status
set -g status-keys vi

# vi keys to resize
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1

# vi keys to select panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# avoid cursor movement messing with resize
set -g repeat-time 200
set -g default-terminal "screen-256color"
#010set-option -ga terminal-overrides ',*-256color*:Tc'
#set-option -ga terminal-overrides ',rxvt-unicode:Tc'
set -g clock-mode-style 12
setw -g clock-mode-colour cyan
set -g base-index 1
setw -g pane-base-index 1

set -g message-style "fg=red"
set -g status-style "fg=#dcdccc"
set -g status on
set status-bg default
set status-position top
set status-interval 1
#set status-left ""
set -g status-right-length 50
# nearly invisible pane borders
#set -g pane-border-style "fg=#324d43,bg=#323d43"
#set -g pane-active-border-style "fg=#323d43,bg=#323d43"

# window selection background
set -g mode-style "bg=black"

# reload config
bind -r r source-file ~/.tmux.conf
