# my window manager config ;)

# Change the default $TERM to tmux-256color
# set-option -ga terminal-overrides ",st-256color:Tc"
# set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -ga terminal-overrides "rxvt-unicode:Tc"
set -g default-terminal "tmux-256color"


unbind C-b
unbind C-a
set -g prefix C-a

# form vim/tmux d/y buffer sync
set -g focus-events

bind-key C-a last-window

unbind |
bind | split-window -h
unbind -
bind - split-window -v

# vi for copy mode
setw -g mode-keys vi

# vi for command status
set -g status-keys vi

# vi keys to resize
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1

# avoid cursor movement messing with resize
set -g repeat-time 200

# colors, clock, etc
setw -g clock-mode-colour cyan
set -g base-index 1
setw -g pane-base-index 1
set -g status off
set -g message-style "fg=red"
