shadow = false;
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
frame-opacity = 0.7;
rounded-corners = true;
corner-radius = 10;
backend = "glx";
vsync = true;

blur:
{
  method = "dual_kawase";
  strenth = 7;
};

blur-background = true;
