shadow = true;
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
frame-opacity = 0.7;
rounded-corners = true;
corner-radius = 15;
backend = "glx";
vsync = true;

blur:
{
  method = "dual_kawase";
  strenth = 5;
};

blur-background = true;
