#!/bin/bash

while true ; do
  BAT=$(acpi | grep 'Battery 0' | sed s/'Battery 0'/'BAT'/ | sed s/,// | sed s/,// | cut --complement -d " " -f2)
  DATE=$(date)
  #BCKLT=$(xbacklight | cut -d "." -f1)
  #TEMP=$(acpi -t | cut -d " " -f 4)

  # doesn't work, I'm only trying it because of my vehement hatred of
  # if statements. It totally would if bash had logical xor.
  # just looked it up, perl doesn't really have it either :(
  #($(pamixer --get-mute) && VOL="MUTE") && !(VOL=$(pamixer --get-volume)) 

  #if $(pamixer --get-mute); then
  #  VOL="MUTE"
  #else
  #  VOL=$(pamixer --get-volume)
  #fi

  echo "| $BAT | $(hostname -s) | $(date +"%H:%M %m/%d") |" #$(hostname -s) for tmux status maybe
  sleep 1
done 

# this is current config tmux status. for termbar proper, add \r behind
# $BCKLT and echo -en
