#!/bin/bash

while true; do
  BAT=$(acpi | sed s/'Battery 0'/'BAT'/ | sed s/,// | sed s/,// | cut --complement -d " " -f2)
  DATE=$(date)
  BCKLT=$(xbacklight | cut -d "." -f1)
  TEMP=$(acpi -t | cut -d " " -f 4,6)
  if $(pamixer --get-mute); then
    VOL="MUTE"
  else
    VOL=$(pamixer --get-volume)
  fi
  echo -en "  $DATE | VOL: $VOL | $BAT | TEMP: $TEMP | LIGHT: $BCKLT\r"
  sleep 1
done 
